#!/usr/bin/env bash
#
# This is the go.d.plugin->netdata version sync script.
# It ingests the updated go.d.plugin version information to netdata repository
#
# Execution Requirements:
#   - hub command
#   - GITHUB_TOKEN variable set with GitHub token
#
# Copyright: SPDX-License-Identifier: GPL-3.0-or-later
#
# Author: Pawel Krupa (@paulfantom)
# Author: Pavlos Emm. Katsoulakis (paul@netdata.cloud)

set -e

# If we are not in netdata git repo, at the top level directory, fail
TOP_LEVEL=$(basename "$(git rev-parse --show-toplevel)")
CWD=$(git rev-parse --show-cdup || echo "")
if [ -n "${CWD}" ] || [ ! "${TOP_LEVEL}" == "go.d.plugin" ]; then
    echo "Run as .travis/$(basename "$0") from top level directory of go.d.plugin local git repository"
    echo "Changelog generation process aborted"
    exit 1
fi

if [ -z ${TRAVIS_TAG+x} ]; then
	echo "Nothing to do - TRAVIS_TAG is not defined (val:${TRAVIS_TAG})"
	exit 0
fi

CHECKSUM_FILE="$(pwd)/bin/sha256sums.txt"
NETDATA_GIT_URL="https://github.com/netdata/netdata.git"
LOCAL_NETDATA_DIR="netdata"
PR_TITLE="Bump go.d.plugin version to ${TRAVIS_TAG}"
PR_MSG="This is an autogenerated pull request. It was triggered by job ${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER} and it should consist of 17 line changes. Please review before merging."
export GIT_MAIL="bot@netdata.cloud"
export GIT_USER="netdatabot"

echo "--- Cloning ${NETDATA_GIT_URL} --- "
git clone "${NETDATA_GIT_URL}" "${LOCAL_NETDATA_DIR}"
cd "${LOCAL_NETDATA_DIR}"

echo "--- Preparing changes for ${NETDATA_GIT_URL} ---"
cp "$CHECKSUM_FILE" packaging/go.d.checksums
sed -i "s/GO_PACKAGE_VERSION=\".*\"/GO_PACKAGE_VERSION=\"${TRAVIS_TAG}\"/g" netdata-installer.sh
git checkout -b new_go_d_version
git add netdata-installer.sh packaging/go.d.checksums
git commit -m "installer: include go.d.plugin version ${TRAVIS_TAG}" --author "${GIT_USER} <${GIT_MAIL}>"

echo "--- Pushing changes to ${NETDATA_GIT_URL} --- "
hub pull-request -p -r paulkatsoulakis,ilyam8 -m "${PR_TITLE}" -m "${PR_MSG}"

echo "Netdata syncing completed successfully!"
